export const FETCH_FORECAST = 'FETCH_FORECAST';
export const CITY_NOT_FOUND = 'CITY_NON_FOUND';
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_FORECASTS = 'FETCH_FORECASTS';
export const SEARCH_TERM = 'SEARCH_TERM';
